default:
  # General variables for all data sets
  harmonization_folder_synid: "syn64176379" # The ID of the Sage_RNASeq_Reprocessing folder on Synapse
  gtf_file: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.primary_assembly.annotation.gtf.gz"
  fasta_file: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.primary_assembly.genome.fa.gz"
  gene_metadata_synid: "syn68742281" # The ID of the gene_metadata file (once it has been uploaded)
  individual_metadata_synid: "syn64759872" #"syn51757646" # Temporary: Use file with corrections to MSBB samples
  biospecimen_metadata_synid: "syn51757645"
  assay_metadata_synid: "syn51757643"

  # Thresholds for validation
  thresholds:
    phred: 20
    reads_mapped: 70
    reads_duplicated: 80
    sex: 2
    DV200: 50
    RIN: 2.5

  # Dataset-specific variables
  Columbia:
    name: "Columbia"
    # Columbia had no sample swaps but has the main data set, one extra sample
    # that was aligned later, and Biggs Institute data
    fastqc_folder_synids: ["syn66498852", "syn68527843", "syn68527919"]
    multiqc_json_synids: ["syn64558076", "syn68527857", "syn68527933"]
    count_matrix_synids: ["syn64289221", "syn68527822", "syn68527907"]
    # This is the only sample for the STG, so it needs to be removed
    stg_remove_id: "BI20-004_stg"

  Mayo_Emory:
    name: "Mayo_Emory"
    # Original Mayo data + sample swap data
    fastqc_folder_synids: ["syn66498946", "syn68243902"]
    multiqc_json_synids: ["syn64558505", "syn68243892"]
    count_matrix_synids: ["syn64176419", "syn68243881"]

  MSSM:
    name: "MSSM"
    # Original MSSM data, MSSM sample swaps sequenced at NYGC, and sample swaps
    # from other centers
    fastqc_folder_synids: ["syn66499292", "syn68243822", "syn68244071"]
    multiqc_json_synids: ["syn64558496", "syn68243798", "syn68244078"]
    count_matrix_synids: ["syn64176431", "syn68243794", "syn68244062"]

  Rush:
    name: "Rush"
    # Rush's sample swaps are included in the original data so there is only one
    # ID per file type
    fastqc_folder_synids: ["syn66499471"]
    multiqc_json_synids: ["syn64558758"]
    count_matrix_synids: ["syn64176441"]
    # These specimen IDs from batch B74 need to be removed
    remove_specimenIDs: ["Div_487", "Div_498", "Div_500", "Div_503", "Div_508", "Div_509", "Div_545"]
    remove_specimenIDs_batch: "B74"
    # Names of the samples to remove as they appear in FastQC data
    remove_samples_fastqc: ["Div_487_S300", "Div_498_S310", "Div_500_S312",
                            "Div_503_S314", "Div_508_S319", "Div_509_S320",
                            "Div_545_S355"]
